### ISSUE TITLE
working only for the host

### ISSUE THREAD

**Issue by parakatins** [ricky-davis/CozyImprovements#2]
it doesn't work for my friend when he enters my lobby, when I enter his lobby it doesn't work for me (we both use the mod)

**Comment by ricky-davis** [comment]
This should now be fixed in version 1.1.0: https://github.com/ricky-davis/CozyImprovements/commit/735304e7972cd57791f261bc177dd2c4ed5bd2a4

Please let me know if you have anymore issues or if this didn't properly fix it.
