### ISSUE TITLE
 bug in the terminal when the game starts

### ISSUE THREAD

**Issue by parakatins** [ricky-davis/CozyImprovements#3]
I noticed that when I enter the ship terminal it is typing the keys I press, when I interact with the terminal it returns to normal, I haven't tested whether this causes any problems in multiplayer, in singleplayer it is just visual apparently

**Comment by ricky-davis** [comment]
Dang, I thought I had fixed that. That one's minor so I'll implement a fix but I'm not going to push a release til something bigger comes along

**Comment by ricky-davis** [comment]
This has been fixed here: https://github.com/ricky-davis/CozyImprovements/commit/f3e87015c06d6b8d15132b38256e9b4113c540cd
It will be in the next release
