### ISSUE TITLE
Breaks TooManySuits Mod

### ISSUE THREAD

**Issue by darkbrewery** [ricky-davis/CozyImprovements#4]
Narrowed it down to "ChargeStationGlow", when set to false the TooManySuits mod works just fine.

**Comment by ricky-davis** [comment]
Is this with the newest version of both mods? I tested mod compatibility between these 2 when v47 released and pushed an update to fix it. I didn't notice any issues after the update, is there something specific that breaks?

**Comment by darkbrewery** [comment]
Newest version of both yes, the toomanysuits mod just breaks, and goes into a loop. With lots of suits they overflow from the rack.

**Comment by darkbrewery** [comment]
![image](https://github.com/ricky-davis/CozyImprovements/assets/806316/84f6774a-14ea-4f46-8cb4-0854ba47cdb8)

**Comment by darkbrewery** [comment]
Maybe it's another conflict somewhere else, here's the mod stack: https://thunderstore.io/c/lethal-company/p/Darkbrewery/DarkbrewerysModPack/

**Comment by ricky-davis** [comment]
I created a new profile with that modpack, which includes configs, and everything worked fine both with and without "ChargeStationGlow" enabled.

**Comment by darkbrewery** [comment]
This is very strange because I just did the same and the issue persists, using r2modman and fresh profile

**Comment by ricky-davis** [comment]
I tested again with another fresh profile to make sure, and again, no issues. I also tested with *just* CozyImprovements and TooManySuits, and found no issues. Can you try testing just those 2 mods for me? I wonder if it's a race condition with your specific PC. 
Either way, nothing is impossible, but knowing how the code works, I cannot imagine how `ChargeStationGlow` specifically would affect anything. Can you post the entire log from your console the next time it happens?

**Comment by darkbrewery** [comment]
This is with just ToomanySuits and Cozyimprovements

`[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (1/3/2024 11:23:07 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Warning:   BepInEx] Plugin [Too Many Suits 1.0.5] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Info   :   BepInEx] Loading [Cozy Improvements 1.2.1]
[Info   :Cozy Improvements] Plugin Cozy Improvements - com.spycibot.cozyimprovements - 1.2.1 is loaded!
[Info   :   BepInEx] Loading [More Suits 1.4.1]
[Info   :More Suits] Plugin More Suits is loaded!
[Info   :   BepInEx] Loading [Too Many Suits 1.0.5]
[Info   :Too Many Suits] TooManySuits Mod Loaded.
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] subcribing to steam callbacks
Setting breakpad minidump AppID = 1966720
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197987065114 [API loaded no]
[Info   : Unity Log] Returning week num: 4
[Info   : Unity Log] week num: 4
[Info   : Unity Log] host button pressed
[Info   : Unity Log] Returning week num: 4
[Info   : Unity Log] Discarding changed settings
[Info   : Unity Log] host button pressed
[Info   : Unity Log] Returning week num: 4
[Info   : Unity Log] Displaying menu message
[Info   : Unity Log] Connection approval callback! Game version of client request:
[Info   : Unity Log] Joining client id: 0; Local/host client id: 0
[Info   : Unity Log] Stopped connection approval callback, as the client in question was the host!
[Warning: Unity Log] [Netcode] You cannot decline the host connection. The connection was automatically approved.
[Info   : Unity Log] started host!
[Info   : Unity Log] are we in a server?: True
[Info   : Unity Log] Lobby has been created
[Warning: Unity Log] [Dissonance:Recording] (22:07:53.321) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.2053098)
[Info   : Unity Log] Enabling connection callbacks in StartOfRound
[Info   : Unity Log] Began listening to SceneManager_OnLoadComplete1 on this client
[Warning: Unity Log] damageTrigger is disabled! Netcode for GameObjects does not support spawning disabled NetworkBehaviours! The InteractTrigger component was skipped during spawn!
[Info   : Unity Log] level id: 1
[Info   : Unity Log] Changing level
[Info   : Unity Log] Item sales percentages #0: 0
[Info   : Unity Log] Item sales percentages #1: 0
[Info   : Unity Log] Item sales percentages #2: 0
[Info   : Unity Log] Item sales percentages #3: 0
[Info   : Unity Log] Item sales percentages #4: 0
[Info   : Unity Log] Item sales percentages #5: 0
[Info   : Unity Log] Item sales percentages #6: 0
[Info   : Unity Log] Item sales percentages #7: 0
[Info   : Unity Log] Item sales percentages #8: 0
[Info   : Unity Log] Item sales percentages #9: 0
[Info   : Unity Log] Item sales percentages #10: 0
[Info   : Unity Log] Item sales percentages #11: 0
[Info   : Unity Log] Item sales percentages #12: 0
[Info   : Unity Log] Loading placed object position as: (3.57, 2.14, -12.95)
[Info   : Unity Log] Saving placed position as: (3.57, 2.14, -12.95)
[Info   : Unity Log] Placing scene object at saved position: Cupboard
[Info   : Unity Log] Loading placed object position as: (-4.89, 1.64, -13.07)
[Info   : Unity Log] Saving placed position as: (-4.89, 1.64, -13.07)
[Info   : Unity Log] Placing scene object at saved position: File Cabinet
[Info   : Unity Log] Loading placed object position as: (-3.81, 1.10, -12.71)
[Info   : Unity Log] Saving placed position as: (-3.81, 1.10, -12.71)
[Info   : Unity Log] Loading placed object position as: (10.14, 1.03, -11.46)
[Info   : Unity Log] Saving placed position as: (10.14, 1.03, -11.46)
[Info   : Unity Log] Placing scene object at saved position: Light switch
[Info   : Unity Log] Loading placed object position as: (8.71, 2.62, -17.45)
[Info   : Unity Log] Saving placed position as: (8.71, 2.62, -17.45)
[Info   : Unity Log] Loading placed object position as: (8.04, 1.96, -11.34)
[Info   : Unity Log] Saving placed position as: (8.04, 1.96, -11.34)
[Info   : Unity Log] Loading placed object position as: (8.02, 0.86, -11.27)
[Info   : Unity Log] Saving placed position as: (8.02, 0.86, -11.27)
[Info   : Unity Log] Loading placed object position as: (6.21, 0.93, -11.17)
[Info   : Unity Log] Saving placed position as: (6.21, 0.93, -11.17)
[Info   : Unity Log] Placing scene object at saved position: Bunkbeds
[Info   : Unity Log] Loading placed object position as: (5.05, 2.04, -16.44)
[Info   : Unity Log] Saving placed position as: (5.05, 2.04, -16.44)
[Info   : Unity Log] Placing scene object at saved position: Terminal
[Info   : Unity Log] Loading placed object position as: (7.45, 1.94, -16.79)
[Info   : Unity Log] Saving placed position as: (7.45, 1.94, -16.79)
[Info   : Unity Log] Loading placed object position as: (10.51, 2.02, -11.26)
[Info   : Unity Log] Saving placed position as: (10.51, 2.02, -11.26)
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SpyciBot.LC.CozyImprovements.CozyImprovements.manageInteractables () (at <e7e9434452084f069350b63f65d7d40c>:0)
SpyciBot.LC.CozyImprovements.CozyImprovements.DoAllTheThings () (at <e7e9434452084f069350b63f65d7d40c>:0)
SpyciBot.LC.CozyImprovements.CozyImprovements.PostfixLoadUnlockables (StartOfRound __instance) (at <e7e9434452084f069350b63f65d7d40c>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::LoadUnlockables>(StartOfRound)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)

[Info   : Unity Log] Item sales percentages #0: 0
[Info   : Unity Log] Item sales percentages #1: 0
[Info   : Unity Log] Item sales percentages #2: 0
[Info   : Unity Log] Item sales percentages #3: 0
[Info   : Unity Log] Item sales percentages #4: 0
[Info   : Unity Log] Item sales percentages #5: 0
[Info   : Unity Log] Item sales percentages #6: 0
[Info   : Unity Log] Item sales percentages #7: 0
[Info   : Unity Log] Item sales percentages #8: 0
[Info   : Unity Log] Item sales percentages #9: 0
[Info   : Unity Log] Item sales percentages #10: 0
[Info   : Unity Log] Item sales percentages #11: 0
[Info   : Unity Log] Item sales percentages #12: 0
[Info   : Unity Log] Group credits: 928
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/LightSwitchContainer/PlacementCollider"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/Cube"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/AnimatedShipDoor/HangarDoorLeft (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ControlDesk.001"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (3)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (7)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/StorageCloset/Cube.000/Cube"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (6)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (8)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (5)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (4)"
[Info   : Unity Log] Taking control of player Player and enabling camera!
[Info   : Unity Log] Starting voice tracking for player: Darkbrewery
[Info   : Unity Log] !!!! ENABLING CAMERA FOR PLAYER: Player
[Info   : Unity Log] !!!! connectedPlayersAmount: 0
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Info   : Unity Log] Has beta?: {hasBeta}
[Info   : Unity Log] Has beta save data: True
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Warning: Unity Log] [Dissonance:Recording] (22:07:57.303) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.1892672)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:0)
`

**Comment by darkbrewery** [comment]
Seems to be fixed just using a fresh save file, weird

**Comment by ricky-davis** [comment]
Odd, the only thing I can think of is one of the mods you used to have, has an object with a similar name to what I target for the Charge Station Glow. I can try to remedy this for future updates

**Comment by ricky-davis** [comment]
Do you have a copy of the broken save? Can you send it to me (here or on Discord @spyci ) I'm seeing a few other people point out this exact error

**Comment by darkbrewery** [comment]
Unfortunately I deleted the save :(

**Comment by ricky-davis** [comment]
Someone was able to find some repro steps and I have fixed this: 39da0e927e7ba9e69220c8a7b7ef50abc7f605fb
